# Generated by Django 2.2.12 on 2020-05-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='title_name',
            new_name='title',
        ),
    ]
