# Generated by Django 2.2.12 on 2020-05-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view_counter', '0002_auto_20200506_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='view_counter.Page')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
