# Generated by Django 2.2.12 on 2020-05-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_counter', '0003_pagecounter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageCounter',
            new_name='Counter',
        ),
    ]
